export enum Paths {
  ABSOLUTE_HOME = '/',
  RELATIVE_HOME = '',
  ABSOLUTE_FOOD = '/food',
  RELATIVE_FOOD = 'food',
  ABSOLUTE_FOOD_ITEM = '/food/:id',
  ABSOLUTE_BEV = '/beverage',
  RELATIVE_BEV = 'beverage',
  ABSOLUTE_BEV_ITEM = '/beverage/:id',
  ABSOLUTE_CALC = '/calculators',
  RELATIVE_CALC = 'calculators',
  ABSOLUTE_CALC_ITEM = '/calculators/:id',
  RELATIVE_TIMER = 'timer',
  ABSOLUTE_TIMER = '/timer',
  CATCH_ALL = '*',
}
